CREATE DATABASE QUANLYBANHANGHASAKI


CREATE TABLE NHANVIEN
(
MANV CHAR(5)
CONSTRAINT PK_NHANVIEN PRIMARY KEY,
 HONV NVARCHAR(100) not null,
 TENNV NVARCHAR(50) not null,
 GIOITINHNV NVARCHAR(10)
 CONSTRAINT CK_PHAI_NHANVIEN CHECK (GIOITINHNV IN(N'NAM', N'NỮ', N'KHAC')),
 NGAYSINH DATE,
 DIACHINV NVARCHAR(100)
 CONSTRAINT DF_DIACHI_NHANVIEN DEFAULT 'CHUA CO',
 DIENTHOAINV NVARCHAR(20),
 EMAILNV  NVARCHAR(50)
 
)
alter table NHANVIEN
ALTER COLUMN NGAYSINH DATETIME
CREATE TABLE KHACHHANG
(
MAKH CHAR(5)
CONSTRAINT PK_KHACHHANG PRIMARY KEY,
 HOKH NVARCHAR(50) not null,
 TENKH NVARCHAR(20) not null,
 GIOITINHKH NVARCHAR(10)
 CONSTRAINT CK_PHAI_KHACHHANG CHECK (GIOITINHKH IN(N'NAM', N'NỮ', N'KHAC')),
 DIACHIKH NVARCHAR(100)
 CONSTRAINT DF_DIACHI_KHACHHANG DEFAULT 'CHUA CO',
 DIENTHOAIKH NVARCHAR(20),
 EMAILKH  NVARCHAR(50)
 
)
CREATE TABLE NHACUNGCAP
(
MANCC CHAR(5) CONSTRAINT PK_NHACUNGCAP PRIMARY KEY,
TENNCC NVARCHAR(50) NOT NULL,
DIACHINCC NVARCHAR(100)
 CONSTRAINT DF_DIACHI_NHACUNGCAP DEFAULT N'CHUA CO',
 DIENTHOAIKH NVARCHAR(30),
WEB  NVARCHAR(50) 
)
CREATE TABLE LOAIHANG
(
 MALH NCHAR(5) CONSTRAINT PK_MALH_LOAIHANG PRIMARY KEY,
 TENLH NCHAR(50)
)
CREATE TABLE MATHANG
(
 MAMH NCHAR(6) CONSTRAINT PK_MAMH_MATHANG PRIMARY KEY,
 TENMH NVARCHAR(150),
 DVT NVARCHAR(20),
 SLTON INT,
 DGNHAP FLOAT,
 DGBAN FLOAT,
 MALH NCHAR(5)
 CONSTRAINT FK_MALH_MATHANG FOREIGN KEY (MALH) REFERENCES LOAIHANG(MALH)
)
CREATE TABLE HOADON
(
 MADH NCHAR(6) CONSTRAINT PK_MADH_DONDH PRIMARY KEY,
 MAKH CHAR(5)
 CONSTRAINT FK_MAKH_DONDH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
 MANV CHAR(5) 
 CONSTRAINT FK_MANV_DONDH FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
 TRIGIA MONEY,
 NGAYLAP DATETIME,
 PTTT NVARCHAR(100)
)
ALTER TABLE HOADON
ALTER COLUMN TRIGIA INT

ALTER TABLE HOADON
ALTER COLUMN NGAYLAP DATE
CREATE TABLE CTHOADON
(
 MADH NCHAR(6) 
 CONSTRAINT FK_MADH_CTDH FOREIGN KEY (MADH) REFERENCES HOADON(MADH),
 MAMH NCHAR(6)
 CONSTRAINT FK_MAMH_CTDH FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH),
 SL INT ,
 DGBAN FLOAT,
 GIAMGIA FLOAT,
 THANHTIEN FLOAT,
 PRIMARY KEY(MADH,MAMH),
 
)
ALTER TABLE CTHOADON
Drop CONSTRAINT FK_MAMH_CTDH 
ALTER TABLE MATHANG
ALTER COLUMN DGBAN FLOAT NOT NULL

ALTER TABLE CTHOADON
ALTER COLUMN DGBAN FLOAT NOT NULL
ALTER TABLE PHIEUNHAP
ALTER COLUMN NGAYNHAP DATE
CREATE TABLE PHIEUNHAP 
( SOPN CHAR (5)  CONSTRAINT PK_SOPN_PHIEUNHAP PRIMARY KEY,
  
  MANV CHAR(5) 
 CONSTRAINT FK_MANV_PHIEUNHAP FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
 MANCC CHAR (5)
 CONSTRAINT FK_MANCC_PHIEUNHAP FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC),
 TRIGIA FLOAT,
  NGAYNHAP DATE ,
   GHICHUNHAP NVARCHAR(100),
   )
   CREATE TABLE PHIEUXUAT
( SOPX CHAR (5)  CONSTRAINT PK_SOPX_PHIEUXUAT PRIMARY KEY,
   NGAYXUAT DATETIME ,
   GHICHUXUAT NVARCHAR(100),
  MANV CHAR(5) 
 CONSTRAINT FK_MANV_PHIEUXUAT FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
 MANCC CHAR (5)
 CONSTRAINT FK_MANCC_PHIEUXUAT FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
   )
     CREATE TABLE CTPHIEUNHAP
( SOPN CHAR (5)  CONSTRAINT FK_SOPN_PHIEUNHAP FOREIGN KEY (SOPN) REFERENCES PHIEUNHAP(SOPN),
 
   MANCC CHAR (5)
 CONSTRAINT FK_MANCC_CTPHIEUNHAP FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC),
  MAMH NCHAR(6)
 CONSTRAINT FK_MAMH_CTPHIEUNHAP FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH),
 SLNHAP INT,
 GIA FLOAT,
 PRIMARY KEY (SOPN)
   )

   CREATE TABLE KHO
   (
   MAKHO CHAR(5) CONSTRAINT PK_MAKHO_KHO PRIMARY KEY ,
   TENKHO NVARCHAR(50) NOT NULL,
   SOPN CHAR(5) ,
    CONSTRAINT FK_SOPN_PN FOREIGN KEY (SOPN) REFERENCES PHIEUNHAP(SOPN),
	SOPX CHAR(5),
	CONSTRAINT FK_SOPX_PX FOREIGN KEY (SOPX) REFERENCES PHIEUXUAT(SOPX),
	DIADIEM NVARCHAR(100) 
   )
   ALTER TABLE CTPHIEUNHAP
   ADD CONSTRAINT FK_MALH_CTPHIEUNHAP FOREIGN KEY (MALH) REFERENCES LOAIHANG(MALH)
   ALTER TABLE MATHANG
   add THANHPHAN nvarchar(200)
    ALTER TABLE MATHANG
   add XUATXU nvarchar(50);
   Create table LOGIN
   (
   USERNAME NVARCHAR(8),
   PASSWORD NVARCHAR(16)
   )