CREATE DATABASE QUANLYBANHANGHASAKI
go
USE QUANLYBANHANGHASAKI
go
CREATE TABLE NHANVIEN
(
MANV CHAR(5)
CONSTRAINT PK_NHANVIEN PRIMARY KEY,
 HONV NVARCHAR(100) not null,
 TENNV NVARCHAR(50) not null,
 GIOITINHNV NVARCHAR(10)
 CONSTRAINT CK_PHAI_NHANVIEN CHECK (GIOITINHNV IN(N'NAM', N'NỮ', N'KHAC')),
 NGAYSINH DATETIME,
 DIACHINV NVARCHAR(100)
 CONSTRAINT DF_DIACHI_NHANVIEN DEFAULT 'CHUA CO',
 DIENTHOAINV NVARCHAR(20),
 EMAILNV  NVARCHAR(50),
 CHUCVU NVARCHAR(20)
)
go
CREATE TABLE KHACHHANG
(
MAKH CHAR(5)
CONSTRAINT PK_KHACHHANG PRIMARY KEY,
 HOKH NVARCHAR(50) not null,
 TENKH NVARCHAR(20) not null,
 GIOITINHKH NVARCHAR(10)
 CONSTRAINT CK_PHAI_KHACHHANG CHECK (GIOITINHKH IN(N'NAM', N'NỮ', N'KHAC')),
 DIACHIKH NVARCHAR(100)
 CONSTRAINT DF_DIACHI_KHACHHANG DEFAULT 'CHUA CO',
 DIENTHOAIKH NVARCHAR(20),
 EMAILKH  NVARCHAR(50)
 
)
go
CREATE TABLE NHACUNGCAP
(
MANCC CHAR(5) CONSTRAINT PK_NHACUNGCAP PRIMARY KEY,
TENNCC NVARCHAR(50) NOT NULL,
DIACHINCC NVARCHAR(100)
 CONSTRAINT DF_DIACHI_NHACUNGCAP DEFAULT N'CHUA CO',
 DIENTHOAINCC NVARCHAR(30) NOT NULL,
WEB  NVARCHAR(50) 
)
go
CREATE TABLE LOAIHANG
(
 MALH NCHAR(5) CONSTRAINT PK_MALH_LOAIHANG PRIMARY KEY,
 TENLH NCHAR(50)
)
go
CREATE TABLE MATHANG
(
 MAMH NCHAR(6) CONSTRAINT PK_MAMH_MATHANG PRIMARY KEY,
 TENMH NVARCHAR(150),
 DVT NVARCHAR(20),
 SLTON INT,
 DGNHAP FLOAT,
 DGBAN FLOAT Not null,
 XUATXU nvarchar(50),
 THANHPHAN nvarchar(200),
 MALH NCHAR(5)
 CONSTRAINT FK_MALH_MATHANG FOREIGN KEY (MALH) REFERENCES LOAIHANG(MALH)
)
go
CREATE TABLE HOADON
(
 MADH NCHAR(6) CONSTRAINT PK_MADH_DONDH PRIMARY KEY,
 MAKH CHAR(5)
 CONSTRAINT FK_MAKH_DONDH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
 MANV CHAR(5) 
 CONSTRAINT FK_MANV_DONDH FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
 TRIGIA MONEY,
 NGAYLAP DATETIME,
 PTTT NVARCHAR(100),
)
go
CREATE TABLE CTHOADON
(
 MADH NCHAR(6) 
 CONSTRAINT FK_MADH_CTDH FOREIGN KEY (MADH) REFERENCES HOADON(MADH),
 MAMH NCHAR(6)
 CONSTRAINT FK_MAMH_CTDH FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH),
 SL INT ,
 DGBAN FLOAT,
 THANHTIEN FLOAT,
 PRIMARY KEY(MADH,MAMH),
 
)
go
CREATE TABLE PHIEUNHAP 
( SOPN CHAR (5)  CONSTRAINT PK_SOPN_PHIEUNHAP PRIMARY KEY,
  MANV CHAR(5) 
 CONSTRAINT FK_MANV_PHIEUNHAP FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
 MANCC CHAR (5)
 CONSTRAINT FK_MANCC_PHIEUNHAP FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC),
 TRIGIA FLOAT,
 NGAYNHAP DATE ,
 GHICHUNHAP NVARCHAR(100),
  )
go
CREATE TABLE PHIEUXUAT
( SOPX CHAR (5)  CONSTRAINT PK_SOPX_PHIEUXUAT PRIMARY KEY,
 TRIGIA FLOAT,
   NGAYXUAT DATETIME ,
   GHICHUXUAT NVARCHAR(100),
  MANV CHAR(5) CONSTRAINT FK_MANV_PHIEUXUAT FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
)
go
CREATE TABLE CTPHIEUNHAP
( SOPN CHAR (5)  CONSTRAINT FK_SOPN_PHIEUNHAP FOREIGN KEY (SOPN) REFERENCES PHIEUNHAP(SOPN),
 MAMH NCHAR(6)
 CONSTRAINT FK_MAMH_CTPHIEUNHAP FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH),
 SLNHAP INT,
 GIA FLOAT,
 PRIMARY KEY (SOPN,MAMH)
 )
 go
CREATE TABLE CTPHIEUXUAT
( SOPX CHAR (5)  CONSTRAINT FK_SOPX_PHIEUXUAT FOREIGN KEY (SOPX) REFERENCES PHIEUXUAT(SOPX),
 MAMH NCHAR(6)
 CONSTRAINT FK_MAMH_CTPHIEUXUAT FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH),
 SLXUAT INT,
 GIA FLOAT,
 PRIMARY KEY (SOPX,MAMH)
 )
   
go 
CREATE TABLE QUYEN 
(
MAQUYEN INT CONSTRAINT PK_MAQUYEN_QUYEN PRIMARY KEY ,
TENQUYEN NVARCHAR(50),
CHUTHIC NVARCHAR(100) CONSTRAINT DF_QUYEN_CHUTHICH DEFAULT (''),
)
GO 
CREATE TABLE USERS
(
ID INT IDENTITY(1,1) NOT NULL ,
MANV NCHAR(10) NOT NULL ,
TENDANGNHAP VARCHAR(50) NOT NULL ,
MATKHAU VARCHAR(50) NOT NULL ,
QUYEN INT CONSTRAINT FK_QUYEN_USERS FOREIGN KEY(QUYEN) REFERENCES QUYEN(MAQUYEN)
)

  

SELECT * FROM NHACUNGCAP

SELECT KHACHHANG.MAKH, HOKH+' '+TENKH AS HOTEN, 
  CASE 
  WHEN COUNT(MADH)=0 THEN NULL
  ELSE COUNT (MADH)
  END AS 'SO HOA DON DA MUA'
 FROM KHACHHANG LEFT  JOIN HOADON  ON KHACHHANG.MAKH= HOADON.MAKH
 GROUP BY KHACHHANG.MAKH,HOKH+' '+TENKH


 SELECT NHANVIEN.MANV, HONV+' '+TENNV AS HOTEN, 
  CASE 
  WHEN COUNT(MADH)=0 THEN NULL
  ELSE COUNT (MADH)
  END AS 'SO HOA DON DA LAP'
 FROM NHANVIEN LEFT  JOIN HOADON  ON NHANVIEN.MANV= HOADON.MANV
 GROUP BY NHANVIEN.MANV, HONV+' '+TENNV

 SELECT NHACUNGCAP.MANCC ,MAMH, SUM(SLNHAP) AS 'TONG SO LUONG HANG ' 
 FROM NHACUNGCAP join PHIEUNHAP ON NHACUNGCAP.MANCC= PHIEUNHAP.MANCC JOIN CTPHIEUNHAP ON PHIEUNHAP.SOPN=CTPHIEUNHAP.SOPN
 GROUP BY NHACUNGCAP.MANCC , MAMH
